# DO NOT CHANGE FILE NAME

specialOfferRootGroup:
  id: 9000000003
  name: Special Offer

preorderRootGroup:
  id: 38153
  name: Pre Order

ignoreGroupList:
  - id: 123456789

paymentMethods:
#   - id: "Credit/Debit Card"
#     name: "Credit/Debit Card"
#     img: ["visa.svg", "master-card.svg", "jcb.svg"]
  - id: "Credit/Debit Card V2"
    name: "Credit/Debit Card"
    img: ["visa.svg", "master-card.svg", "jcb.svg", "amex.svg"]
#   - id: "Amex"
#     name: "Amex"
#     img: ["amex.svg"]
#   - id: "Vplus Wallet"
#     name: "Vplus Wallet"
#     img: ["wallet-logo.svg"]
  - id: "Thai QR"
    name: "Thai QR"
    img: ["thai_qr.png"]
#  - id: "Other"
#    name: "Other"
#    img: ["thai_qr.png","alipay_logo.jpg", "wechat-pay.svg", "union.svg"]
  - id: "Wechat"
    name: "Wechat"
    img: ["wechat-pay.svg"]
  - id: "Alipay"
    name: "Alipay"
    img: ["alipay_logo.jpg"]
  - id: "Vplus Wallet V2"
    name: "Vplus Wallet"
    img: ["wallet-logo.svg"]
